### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by dr0i**
Added `npm install` to the README.
~- add rdf-parser-jsonld to package.json~

### CODE REVIEW

**Comment by csarven** [comment]
The dependencies eventually fetch `rdf-parser-jsonld` :

`rdf-store-ldp` -> `rdf-formats-common` -> `rdf-parser-jsonld`

Are you getting a particular error? Which npm version are you using?

**Comment by dr0i** [comment]
``
$ npm -v
5.5.1
``
Unfamiliar with `npm` I did just what the mayktso-README said (`$ node index.js`) which leads to these kind of errors:

> $ node index.js        
module.js:471
    throw err;
    ^
Error: Cannot find module 'rdf-parser-rdfa'

and so on. `$ npm install` installs all the dependencies automatically so I put that into the README as a pretext.
The file `pachage.json` is versionised and at the end of `$ npm install` the module `rdf-parser-jsonld` was added to that file so a `$ git status` shows it as changed, so I commited that changed file, too.

**Comment by csarven** [comment]
That's odd. The instructions you've created look good, but I don't think the package.json needs the rdf-parser-jsonld . If you do `npm install` (using the existing package.json from the repo) does it work for you? If so, we just need to update the README

**Comment by dr0i** [comment]
@csarven you are right. Amended the commit.

**Comment by csarven** [comment]
Thanks!

**Pull request merged**
